<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>Newsletter</title>
    <meta name="description" content="Module JS1 - Exercice Icons">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link href="css/lib/normalize.css" rel="stylesheet">
    <link href="css/lib/layout.css" rel="stylesheet">
    <link href="css/lib/theme.css" rel="stylesheet">
    <link href="css/newsletter.css" rel="stylesheet">
</head>

<body>
    <header class="banner">
        <a class="banner-link" href="index.php">
            <strong class="banner-title">Abonnez-vous à notre newsletter ! </strong>
            <small>C'est gratuit !</small>
        </a>
    </header>
    <main class="project">
        <form id="subscribe-form" action="index.php" method="POST">

            <?php if (isset($success)) : ?>
                <p class="message success"><?= $success; ?></p>
            <?php endif; ?>
            <fieldset>
                <legend>Abonnez-vous à la newsletter !</legend>
                <div class="field-list">
                    <label for="email">Adresse email</label>
                    <input type="email" name="email" id="email" value="<?= $email ?>">
                    <?php if (isset($errors['email'])) : ?>
                        <p class="message error"><?= $errors['email']; ?></p>
                    <?php endif; ?>
                </div>
                <div class="field-list">
                    <label for="firstname">Prénom</label>
                    <input type="text" name="firstname" id="prenom" value="<?= $firstname ?>">
                    <?php if (isset($errors['firstname'])) : ?>
                        <p class="message error"><?= $errors['firstname']; ?></p>
                    <?php endif; ?>
                </div>
                <div class="field-list">
                    <label for="lastname">Nom</label>
                    <input type="text" name="lastname" id="nom" value="<?= $lastname ?>">
                    <?php if (isset($errors['lastname'])) : ?>
                        <p class="message error"><?= $errors['lastname']; ?></p>
                    <?php endif; ?>
                </div>
                <div class="field-list">
                    <label for="origin">Comment avez-vous connu notre site ?</label>
                    <select name="origin" id="origin">
                        <option value="" hidden></option>
                        <!-- On boucle les origines qui se trouve dans la BDD pour les afficher -->
                        <?php foreach ($originsFromBDD as $originFromBDD) : ?>
                            <option value="<?= $originFromBDD['id']; ?>" <?php if(isset($origin) AND $origin == $originFromBDD['id']) { echo "selected"; }?>><?= $originFromBDD['origin_label']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <!-- Si aucune origine n'est sélectionnée, on affiche un message d'erreur -->
                    <?php if (isset($errors['origin'])) : ?>
                        <p class="message error"><?= $errors['origin']; ?></p>
                    <?php endif; ?>
                </div>
                <div class="field-list">
                    <label>Quels sont vos centres d'intérêts ?</label>
                    <br>
                    <!-- On boucle les intérêts qui se trouve dans la BDD pour les afficher -->
                    <?php foreach ($interestsFromBDD as $interestFromBDD) : ?>
                        <input type="checkbox" name="interest[]" id="<?= $interestFromBDD['id']; ?>" value="<?= $interestFromBDD['id']; ?>" <?php if(isset($_POST['interest']) AND in_array($interestFromBDD['id'], $_POST['interest'])) { echo "checked"; }?>>
                        <label for="<?= $interestFromBDD['id']; ?>"><?= $interestFromBDD['interest_label']; ?></label>
                        <br>
                    <?php endforeach; ?>
                    <!-- Si aucun intérêt n'est sélectionné, on affiche un message d'erreur -->
                    <?php if (isset($errors['interest'])) : ?>
                        <p class="message error"><?= $errors['interest']; ?></p>
                    <?php endif; ?>
                </div>
                <input type="submit" value="Valider" class="btn">
            </fieldset>
        </form>
    </main>

    <footer id="mentions" class="mentions">
        <p><strong> &copy; Olivier Meunier</strong>
    </footer>

</body>

</html>